name: packager_common
description: A starting point for Dart libraries or applications.
version: 1.0.0+3
# homepage: https://www.example.com
# author: Samuel Zuniga Vanoye <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  equatable: ^0.1.0
  bloc: ^0.12.0
  path: ^1.4.1
  http: 0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
